version: '3'
services:
  nginx:
    image: nginx
    restart: always
    network_mode: host
    volumes:
      - ./password:/usr/local/passwd
      - ./fullchain.cer:/usr/local/bin/cert.pem
      - ./fly97.fun.key:/usr/local/bin/key.pem
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /mnt:/mnt
      - /dev/shm:/dev/shm
      - ./index.html:/index.html
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:4.4.5
    container_name: qbittorrent
    restart: always
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
      - WEBUI_PORT=8080
    volumes:
      - ./config:/config
      - /mnt/:/mnt
    network_mode: host
  singbox:
    image: fly97/singbox
    container_name: singbox
    restart: always
    volumes:
      - ./singbox.json:/usr/local/bin/config.json
