version: '3'
services:
  naiveproxy:
    image: ghcr.io/flyzstu/naiveproxy
    restart: always
    network_mode: host
    volumes:
      - ./Caddyfile:/usr/local/bin/Caddyfile
      - ./fullchain.cer:/usr/local/bin/cert.pem
      - ./fly97.fun.key:/usr/local/bin/cert.key
      - ./index.html:/index.html
      - /dev/shm:/dev/shm
    command: --config /usr/local/bin/Caddyfile
  nginx:
    image: nginx
    restart: always
    network_mode: host
    volumes:
      - ./password:/usr/local/passwd
      - ./fullchain.cer:/usr/local/bin/cert.pem
      - ./fly97.fun.key:/usr/local/bin/key.pem
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /mnt:/mnt
      - /dev/shm:/dev/shm
      - ./index.html:/index.html
  grpc:
    image: ghcr.io/flyzstu/xray
    restart: always
    network_mode: host
    volumes:
      - ./grpc.json:/usr/local/bin/config.json
      - /dev/shm:/dev/shm
    command: -c /usr/local/bin/config.json
  hysteria:
    image: ghcr.io/flyzstu/hysteria
    restart: always
    network_mode: host
    volumes:
      - ./hysteria.json:/usr/local/bin/config.json
      - ./fullchain.cer:/usr/local/bin/cert.pem
      - ./fly97.fun.key:/usr/local/bin/key.pem
    command: -c /usr/local/bin/config.json server
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:4.4.5
    container_name: qbittorrent
    restart: always
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
      - WEBUI_PORT=8080
    volumes:
      - ./config:/config
      - /mnt/:/mnt
    network_mode: host
    deploy:
      resources:
        limits:
         memory: 128M